name: Build & Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            output: watermark-linux-amd64
          - goos: linux
            goarch: arm64
            output: watermark-linux-arm64
          - goos: darwin
            goarch: amd64
            output: watermark-darwin-amd64
          - goos: darwin
            goarch: arm64
            output: watermark-darwin-arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Build ${{ matrix.output }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -o ./build/${{ matrix.output }} .

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.output }}
          path: ./build/${{ matrix.output }}

  Tag-and-Release:
    needs: Build
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: write
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./build
          merge-multiple: true

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          tag_prefix: v

      - name: Create new release
        if: ${{ steps.tag_version.outputs.new_tag != '' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Watermark (${{ steps.tag_version.outputs.new_tag }})
          body: |
            Release **${{ steps.tag_version.outputs.new_tag }}**

            ${{ steps.tag_version.outputs.changelog }}

            ---
            Commit: ${{ github.sha }}
          files: ./build/*
          draft: false
          prerelease: false
          make_latest: true

  Deploy-Formula:
    needs: Tag-and-Release
    if: ${{ needs.Tag-and-Release.outputs.new_tag != '' }}
    uses: ./.github/workflows/brew.yml
    with:
      version: ${{ needs.Tag-and-Release.outputs.new_tag }}
    secrets:
      HOMEBREW_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
